import mongoose from "mongoose";

const orderItemSchema = new mongoose.Schema({
    product: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Product",
        required: true,
    },
    name: {
        type: String,
        required: true,
    },
    quantity: {
        type: Number,
        required: true,
        min: [1, "Quantity must be at least 1"],
    },
    weight: {
        type: String,
        default: null,
    },
    price: {
        type: Number,
        required: true,
    },
    image: {
        type: String,
        default: null,
    },
}, { _id: false });

const orderSchema = new mongoose.Schema(
    {
        orderNumber: {
            type: String,
            unique: true,
            // Not required - will be generated by pre-save hook
        },
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null, // null for guest orders
        },
        // Customer Information
        customerInfo: {
            firstName: { type: String, required: true },
            lastName: { type: String, required: true },
            email: { type: String, required: true },
            phone: { type: String, required: true },
            companyName: { type: String, default: "" },
        },
        // Billing Address
        billingAddress: {
            streetAddress: { type: String, required: true },
            apartment: { type: String, default: "" },
            townCity: { type: String, required: true },
            state: { type: String, default: "" },
            zipCode: { type: String, default: "" },
            country: { type: String, default: "" },
        },
        // Shipping Address
        shippingAddress: {
            streetAddress: { type: String, required: true },
            apartment: { type: String, default: "" },
            townCity: { type: String, required: true },
            state: { type: String, default: "" },
            zipCode: { type: String, default: "" },
            country: { type: String, default: "" },
        },
        // Order Items
        items: {
            type: [orderItemSchema],
            required: true,
        },
        // Pricing
        subtotal: {
            type: Number,
            required: true,
            min: 0,
        },
        shippingCost: {
            type: Number,
            default: 0,
            min: 0,
        },
        discount: {
            type: Number,
            default: 0,
            min: 0,
        },
        total: {
            type: Number,
            required: true,
            min: 0,
        },
        // Payment Information
        paymentMethod: {
            type: String,
            enum: ["bankTransfer", "cod"],
            required: true,
        },
        paymentStatus: {
            type: String,
            enum: ["pending", "paid", "failed", "refunded"],
            default: "pending",
        },
        receiptUrl: {
            type: String,
            default: null, // For bank transfer receipts
        },
        // Order Status
        status: {
            type: String,
            enum: ["pending", "processing", "shipped", "delivered", "cancelled"],
            default: "pending",
        },
        // Additional Information
        couponCode: {
            type: String,
            default: null,
        },
        notes: {
            type: String,
            default: "",
        },
    },
    {
        timestamps: true,
    }
);

// Generate unique order number before saving
orderSchema.pre("save", async function (next) {
    if (!this.orderNumber) {
        const timestamp = Date.now();
        const random = Math.floor(Math.random() * 10000);
        this.orderNumber = `ORD-${timestamp}-${random}`;
    }
    next();
});

// Index for faster queries
// Note: orderNumber already has unique: true which creates an index automatically
// Removed explicit user index to avoid duplicate index warning
// Can add back if needed: orderSchema.index({ user: 1 }, { sparse: true });
orderSchema.index({ "customerInfo.email": 1 });
orderSchema.index({ createdAt: -1 });

const Order = mongoose.model("Order", orderSchema);

export default Order;
